### ISSUE TITLE
KeyError: 'GA'

### ISSUE THREAD

**Issue by jessica-agnewblais** [getian107/PRScs#11] opened 2020-05-04 08:08 UTC
Hello Tian,

There are a couple of issues with the set-up of my summary statistics that seem to 
be causing issues. First, whenever the A1/A2 alleles differ from a single nucleotide, 
for example, GA rather than just A. Second, it sounds like it will be an issue when 
the SNP is not in rs format, for example chr1:956061. Is there any way to remedy this 
beyond just deleting these variants from the file? 

Many thanks,
Jess

**Comment by getian107** [comment] 2020-05-04 15:16
Hi Jess- the issue caused by non-ATGC alleles should have be fixed in the latest version of the software. For SNPs not in rs format, you need to convert them to rs IDs before using the software to maximize predictive power. You can use a reference panel (e.g., the 1000 Genomes data) or the `snpinfo_1kg_hm3` file that comes with PRScs to do the mapping.

**Comment by jessica-agnewblais** [comment] 2020-05-04 15:24
Thanks so much for your quick response, that is really helpful!

Best,
Jess

On 4 May 2020, at 16:16, Tian Ge <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Jess- the issue caused by non-ATGC alleles should have be fixed in the latest version of the software. For SNPs not in rs format, you need to convert them to rs IDs before using the software to maximize predictive power. You can use a reference panel (e.g., the 1000 Genomes data) or the snpinfo_1kg_hm3 file that comes with PRScs to do the mapping.

**Closed as completed** 2020-05-04 21:37 UTC
